- name: cron feeder
  # The “name” parameter should be unique,
  # and changing the “name” value will result in a new cron task being created (or a different one being removed).
  # remove via state: absent
  cron:
    name: feed chickens if underfed
    hour: "7,13,17"
    minute: "0"
    state: present
    job: "node {{ BIN_DIR }}/feeder.js"

- name: daily reporting
  cron:
    name: feed report
    hour: "23"
    minute: "59"
    state: present
    job: "node {{ BIN_DIR }}/report.js"

- name: update btcpayserver
  cron:
    name: update btcpayserver
    hour: "1"
    minute: "0"
    state: present
    job: btcpay-update.sh
