---
- name: fetch latest git version
  tags: git
#  register: repo
#  set_fact:
#    repo_changed: repo.changed
  git:
    repo: "https://github.com/j-chimienti/pollofeed.git"
    update: yes
    dest: "./{{APP_DIR}}"


- name: cron
  include: cron.yml
  tags: cron


- name: env files
  tags: env_files
  include: copyEnv.yml


- name: reboot
  tags: reboot
  #when: repo_changed
  include: reboot.yml
