---
- name: fetch latest git version
  tags: git
#  register: repo
#  set_fact:
#    repo_changed: repo.changed
  git:
    repo: "https://github.com/j-chimienti/pollofeed.git"
    update: yes
    dest: "./{{APP_DIR}}"

- name: env files
  tags: env_files
  with_items:
    - .env
    - .env.mongo
    - .env.development
  copy:
    src: "../../../../{{ item }}"
    dest: "./{{APP_DIR}}/{{ item }}"


- name: build docker container
  command: docker-compose up --build -d
  tags: reboot
  args:
    chdir: "./{{APP_DIR}}"


- name: cron
  include: cron.yml
  tags: cron
