version: '3.4'
services:
  db:
    container_name: db
    image: mongo
    volumes:
      - /mongo/data/pollofeed:/data/db
    env_file:
      - .env.mongo
    ports:
      - 27017:27017
    restart: always
    networks:
      - nginxproxy
  pollofeed:
    container_name: pollofeed
#    volumes:
#      - /var/log/docker:/var/log
    build: .
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - nginxproxy
    env_file:
      - .env
    environment:
      POLLOFEED_MONGO_URI: "mongodb://${MONGO_APP_USER}:${MONGO_APP_PASSWORD}@db/${POLLOFEED_DB_NAME}"
    ports:
      - "${PORT}:${PORT}"

networks:
  nginxproxy:
    external:
      name: nginxproxy


