---

- name: apt install
  become: yes
  become_method: sudo
  vars:
    packages:
      - vim
      - motion
      - nodejs
      - npm
  apt:
    name: "{{ packages }}"
    update_cache: yes

- name: copy files
  tags: copy_files
  with_items:
    - pollofeed.py
    - requirements.txt
    - ngrok.yml
    - update-hostname.py
    - setup.py
    - config.yml
  copy:
    src: "{{ item }}"
    dest: "{{ pollofeed_dir }}/{{ item }}"

- name: install requirements
  tags: install_requirements
  args:
    chdir: "{{ pollofeed_dir }}"
  pip:
    requirements: requirements.txt


- name: update npm
  become: yes
  tags: update npm
  command: npm i -g npm

- name: install ngrok
  become: yes
  tags: install_ngrok
  command: npm i --unsafe-perm -g ngrok


### TODO: ENABLE SERVICES
