- name: service
  copy:
    src: pollofeed.service
    dest: /etc/systemd/system/pollofeed.service

- name: enable
  system:
    name: pollofeed
    enabled: yes
    started: yes

- name: reload
  command: sudo systemctl daemon-reload
